server:
  port: 8080

application:
  security:
    jwt:
      secret-key: 8z6h+SoGKYYsWlR5QpqZUNlR2D2WrAy4md6AwQXzjCI=
      expiration: 3600000
      refresh-token:
        expiration: 43200000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportsdb
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#    show-sql: false